// const s = [
//   {
//     name: "Santiago",
//     temperaments: "Curious, Fun-loving, Active, Aloof",
//     id: "13032414-8fda-4430-b7d6-f29c5359b87a",
//     life_span: " infinitos",
//     height: "12-23",
//     weight: "12-34",
//     image: "https://images3.alphacoders.com/131/thumb-1920-1314151.jpg",
//     created: true,
//   },
//   {
//     name: "Affenpinscher",
//     temperaments: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
//     id: 1,
//     life_span: "10 - 12 years",
//     height: "23 - 29",
//     weight: "3 - 6",
//     image: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
//     created: false,
//   },
//   {
//     name: "Afghan Hound",
//     temperaments: "Aloof, Clownish, Dignified, Independent, Happy",
//     id: 2,
//     life_span: "10 - 13 years",
//     height: "64 - 69",
//     weight: "23 - 27",
//     image: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
//     created: false,
//   },
//   {
//     name: "African Hunting Dog",
//     temperaments: "Wild, Hardworking, Dutiful",
//     id: 3,
//     life_span: "11 years",
//     height: "76",
//     weight: "20 - 30",
//     image: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
//     created: false,
//   },
//   {
//     name: "Airedale Terrier",
//     temperaments:
//       "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
//     id: 4,
//     life_span: "10 - 13 years",
//     height: "53 - 58",
//     weight: "18 - 29",
//     image: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
//     created: false,
//   },
//   {
//     name: "Akbash Dog",
//     temperaments: "Loyal, Independent, Intelligent, Brave",
//     id: 5,
//     life_span: "10 - 12 years",
//     height: "71 - 86",
//     weight: "41 - 54",
//     image: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
//     created: false,
//   },
//   {
//     name: "Akita",
//     temperaments:
//       "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
//     id: 6,
//     life_span: "10 - 14 years",
//     height: "61 - 71",
//     weight: "29 - 52",
//     image: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
//     created: false,
//   },
//   {
//     name: "Alapaha Blue Blood Bulldog",
//     temperaments: "Loving, Protective, Trainable, Dutiful, Responsible",
//     id: 7,
//     life_span: "12 - 13 years",
//     height: "46 - 61",
//     weight: "25 - 41",
//     image: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
//     created: false,
//   },
//   {
//     name: "Alaskan Husky",
//     temperaments: "Friendly, Energetic, Loyal, Gentle, Confident",
//     id: 8,
//     life_span: "10 - 13 years",
//     height: "58 - 66",
//     weight: "17 - 23",
//     image: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
//     created: false,
//   },
//   {
//     name: "Alaskan Malamute",
//     temperaments: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
//     id: 9,
//     life_span: "12 - 15 years",
//     height: "58 - 64",
//     weight: "29 - 45",
//     image: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
//     created: false,
//   },
//   {
//     name: "American Bulldog",
//     temperaments:
//       "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
//     id: 10,
//     life_span: "10 - 12 years",
//     height: "56 - 69",
//     weight: "27 - 54",
//     image: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
//     created: false,
//   },
//   {
//     name: "American Bully",
//     temperaments:
//       "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
//     id: 11,
//     life_span: "8 – 15 years",
//     height: "36 - 43",
//     weight: "14 - 68",
//     image: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
//     created: false,
//   },
//   {
//     name: "American Eskimo Dog",
//     temperaments: "Friendly, Alert, Reserved, Intelligent, Protective",
//     id: 12,
//     life_span: "12 - 15 years",
//     height: "38 - 48",
//     weight: "9 - 18",
//     image: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
//     created: false,
//   },
//   {
//     name: "American Eskimo Dog (Miniature)",
//     temperaments: "Friendly, Alert, Reserved, Intelligent, Protective",
//     id: 13,
//     life_span: "13 – 15 years",
//     height: "23 - 30",
//     weight: "3 - 5",
//     image: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
//     created: false,
//   },
//   {
//     name: "American Foxhound",
//     temperaments:
//       "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
//     id: 14,
//     life_span: "8 - 15 years",
//     height: "53 - 71",
//     weight: "29 - 34",
//     image: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
//     created: false,
//   },
//   {
//     name: "American Pit Bull Terrier",
//     temperaments:
//       "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
//     id: 15,
//     life_span: "10 - 15 years",
//     height: "43 - 53",
//     weight: "14 - 27",
//     image: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
//     created: false,
//   },
//   {
//     name: "American Staffordshire Terrier",
//     temperaments: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
//     id: 16,
//     life_span: "12 - 15 years",
//     height: "43 - 48",
//     weight: "23 - 27",
//     image: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
//     created: false,
//   },
//   {
//     name: "American Water Spaniel",
//     temperaments:
//       "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
//     id: 17,
//     life_span: "10 - 12 years",
//     height: "38 - 46",
//     weight: "11 - 20",
//     image: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Anatolian Shepherd Dog",
//     temperaments: "Steady, Bold, Independent, Confident, Intelligent, Proud",
//     id: 18,
//     life_span: "11 - 13 years",
//     height: "69 - 74",
//     weight: "36 - 68",
//     image: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Appenzeller Sennenhund",
//     temperaments: "Reliable, Fearless, Energetic, Lively, Self-assured",
//     id: 19,
//     life_span: "12 – 14 years",
//     height: "51 - 56",
//     weight: "22 - 25",
//     image: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
//     created: false,
//   },
//   {
//     name: "Australian Cattle Dog",
//     temperaments: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
//     id: 21,
//     life_span: "12 - 14 years",
//     height: "43 - 51",
//     weight: "20 - 28",
//     image: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
//     created: false,
//   },
//   {
//     name: "Australian Kelpie",
//     temperaments: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
//     id: 22,
//     life_span: "10 - 13 years",
//     height: "43 - 51",
//     weight: "14 - 21",
//     image: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Australian Shepherd",
//     temperaments: "Good-natured, Affectionate, Intelligent, Active, Protective",
//     id: 23,
//     life_span: "12 - 16 years",
//     height: "46 - 58",
//     weight: "16 - 29",
//     image: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
//     created: false,
//   },
//   {
//     name: "Australian Terrier",
//     temperaments:
//       "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
//     id: 24,
//     life_span: "15 years",
//     height: "25 - 28",
//     weight: "6 - 7",
//     image: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
//     created: false,
//   },
//   {
//     name: "Azawakh",
//     temperaments: "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
//     id: 25,
//     life_span: "10 - 13 years",
//     height: "58 - 74",
//     weight: "15 - 25",
//     image: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
//     created: false,
//   },
//   {
//     name: "Barbet",
//     temperaments: "Obedient, Companionable, Intelligent, Joyful",
//     id: 26,
//     life_span: "13 – 15 years",
//     height: "51 - 66",
//     weight: "18 - 29",
//     image: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
//     created: false,
//   },
//   {
//     name: "Basenji",
//     temperaments:
//       "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
//     id: 28,
//     life_span: "10 - 12 years",
//     height: "41 - 43",
//     weight: "10 - 11",
//     image: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
//     created: false,
//   },
//   {
//     name: "Basset Bleu de Gascogne",
//     temperaments: "Affectionate, Lively, Agile, Curious, Happy, Active",
//     id: 29,
//     life_span: "10 - 14 years",
//     height: "33 - 38",
//     weight: "16 - 18",
//     image: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
//     created: false,
//   },
//   {
//     name: "Basset Hound",
//     temperaments:
//       "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
//     id: 30,
//     life_span: "12 - 15 years",
//     height: "36",
//     weight: "23 - 29",
//     image: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
//     created: false,
//   },
//   {
//     name: "Beagle",
//     temperaments:
//       "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
//     id: 31,
//     life_span: "13 - 16 years",
//     height: "33 - 38",
//     weight: "9 - 16",
//     image: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
//     created: false,
//   },
//   {
//     name: "Bearded Collie",
//     temperaments: "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
//     id: 32,
//     life_span: "12 - 14 years",
//     height: "51 - 56",
//     weight: "20 - 25",
//     image: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
//     created: false,
//   },
//   {
//     name: "Beauceron",
//     temperaments: "Fearless, Friendly, Intelligent, Protective, Calm",
//     id: 33,
//     life_span: "10 - 12 years",
//     height: "61 - 70",
//     weight: "36 - 50",
//     image: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
//     created: false,
//   },
//   {
//     name: "Bedlington Terrier",
//     temperaments: "Affectionate, Spirited, Intelligent, Good-tempered",
//     id: 34,
//     life_span: "14 - 16 years",
//     height: "38 - 41",
//     weight: "8 - 10",
//     image: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
//     created: false,
//   },
//   {
//     name: "Belgian Malinois",
//     temperaments:
//       "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
//     id: 36,
//     life_span: "12 - 14 years",
//     height: "56 - 66",
//     weight: "18 - 36",
//     image: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
//     created: false,
//   },
//   {
//     name: "Belgian Tervuren",
//     temperaments: "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
//     id: 38,
//     life_span: "10 - 12 years",
//     height: "56 - 66",
//     weight: "18 - 29",
//     image: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
//     created: false,
//   },
//   {
//     name: "Bernese Mountain Dog",
//     temperaments: "Affectionate, Loyal, Intelligent, Faithful",
//     id: 41,
//     life_span: "7 - 10 years",
//     height: "58 - 70",
//     weight: "29 - 54",
//     image: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
//     created: false,
//   },
//   {
//     name: "Bichon Frise",
//     temperaments: "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
//     id: 42,
//     life_span: "15 years",
//     height: "24 - 29",
//     weight: "5 - 8",
//     image: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
//     created: false,
//   },
//   {
//     name: "Black and Tan Coonhound",
//     temperaments:
//       "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
//     id: 43,
//     life_span: "10 - 12 years",
//     height: "58 - 69",
//     weight: "29 - 45",
//     image: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
//     created: false,
//   },
//   {
//     name: "Bloodhound",
//     temperaments: "Stubborn, Affectionate, Gentle, Even Tempered",
//     id: 45,
//     life_span: "8 - 10 years",
//     height: "58 - 69",
//     weight: "36 - 50",
//     image: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
//     created: false,
//   },
//   {
//     name: "Bluetick Coonhound",
//     temperaments: "Friendly, Intelligent, Active",
//     id: 47,
//     life_span: "12 - 14 years",
//     height: "53 - 69",
//     weight: "20 - 36",
//     image: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Boerboel",
//     temperaments: "Obedient, Confident, Intelligent, Dominant, Territorial",
//     id: 48,
//     life_span: "10 - 12 years",
//     height: "56 - 69",
//     weight: "50 - 91",
//     image: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
//     created: false,
//   },
//   {
//     name: "Border Collie",
//     temperaments: "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
//     id: 50,
//     life_span: "12 - 16 years",
//     height: "46 - 56",
//     weight: "14 - 20",
//     image: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
//     created: false,
//   },
//   {
//     name: "Border Terrier",
//     temperaments:
//       "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
//     id: 51,
//     life_span: "12 - 14 years",
//     height: "28 - 41",
//     weight: "5 - 7",
//     image: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
//     created: false,
//   },
//   {
//     name: "Boston Terrier",
//     temperaments: "Friendly, Lively, Intelligent",
//     id: 53,
//     life_span: "11 - 13 years",
//     height: "41 - 43",
//     weight: "5 - 11",
//     image: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
//     created: false,
//   },
//   {
//     name: "Bouvier des Flandres",
//     temperaments: "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
//     id: 54,
//     life_span: "10 - 15 years",
//     height: "60 - 70",
//     weight: "32 - 50",
//     image: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
//     created: false,
//   },
//   {
//     name: "Boxer",
//     temperaments:
//       "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
//     id: 55,
//     life_span: "8 - 10 years",
//     height: "55 - 64",
//     weight: "23 - 32",
//     image: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Boykin Spaniel",
//     temperaments:
//       "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
//     id: 56,
//     life_span: "10 - 14 years",
//     height: "36 - 46",
//     weight: "11 - 18",
//     image: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
//     created: false,
//   },
//   {
//     name: "Bracco Italiano",
//     temperaments:
//       "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
//     id: 57,
//     life_span: "10 - 12 years",
//     height: "55 - 67",
//     weight: "25 - 40",
//     image: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Briard",
//     temperaments:
//       "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
//     id: 58,
//     life_span: "10 - 12 years",
//     height: "56 - 69",
//     weight: "32 - 41",
//     image: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
//     created: false,
//   },
//   {
//     name: "Brittany",
//     temperaments: "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
//     id: 59,
//     life_span: "12 - 14 years",
//     height: "44 - 52",
//     weight: "14 - 20",
//     image: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
//     created: false,
//   },
//   {
//     name: "Bull Terrier",
//     temperaments: "Trainable, Protective, Sweet-Tempered, Keen, Active",
//     id: 61,
//     life_span: "10 - 12 years",
//     height: "53 - 56",
//     weight: "23 - 32",
//     image: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
//     created: false,
//   },
//   {
//     name: "Bull Terrier (Miniature)",
//     temperaments:
//       "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
//     id: 62,
//     life_span: "11 – 14 years",
//     height: "25 - 36",
//     weight: "11 - 15",
//     image: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
//     created: false,
//   },
//   {
//     name: "Bullmastiff",
//     temperaments:
//       "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
//     id: 64,
//     life_span: "8 - 12 years",
//     height: "61 - 69",
//     weight: "45 - 59",
//     image: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
//     created: false,
//   },
//   {
//     name: "Cairn Terrier",
//     temperaments: "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
//     id: 65,
//     life_span: "14 - 15 years",
//     height: "23 - 25",
//     weight: "6 - 6",
//     image: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
//     created: false,
//   },
//   {
//     name: "Cane Corso",
//     temperaments: "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
//     id: 67,
//     life_span: "10 - 11 years",
//     height: "60 - 70",
//     weight: "40 - 54",
//     image: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
//     created: false,
//   },
//   {
//     name: "Cardigan Welsh Corgi",
//     temperaments:
//       "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
//     id: 68,
//     life_span: "12 - 14 years",
//     height: "27 - 32",
//     weight: "11 - 17",
//     image: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
//     created: false,
//   },
//   {
//     name: "Catahoula Leopard Dog",
//     temperaments:
//       "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
//     id: 69,
//     life_span: "10 - 12 years",
//     height: "51 - 66",
//     weight: "23 - 43",
//     image: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
//     created: false,
//   },
//   {
//     name: "Caucasian Shepherd (Ovcharka)",
//     temperaments: "Alert, Quick, Dominant, Powerful, Calm, Strong",
//     id: 70,
//     life_span: "10 - 12 years",
//     height: "61 - 85",
//     weight: "36 - 45",
//     image: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
//     created: false,
//   },
//   {
//     name: "Cavalier King Charles Spaniel",
//     temperaments:
//       "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
//     id: 71,
//     life_span: "10 - 14 years",
//     height: "30 - 33",
//     weight: "6 - 8",
//     image: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
//     created: false,
//   },
//   {
//     name: "Chesapeake Bay Retriever",
//     temperaments:
//       "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
//     id: 76,
//     life_span: "10 - 13 years",
//     height: "53 - 66",
//     weight: "25 - 36",
//     image: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
//     created: false,
//   },
//   {
//     name: "Chinese Crested",
//     temperaments: "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
//     id: 78,
//     life_span: "10 - 14 years",
//     height: "28 - 33",
//     weight: "5 - 6",
//     image: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Chinese Shar-Pei",
//     temperaments:
//       "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
//     id: 79,
//     life_span: "10 years",
//     height: "46 - 51",
//     weight: "20 - 27",
//     image: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
//     created: false,
//   },
//   {
//     name: "Chinook",
//     temperaments: "Friendly, Alert, Dignified, Intelligent, Calm",
//     id: 80,
//     life_span: "12 - 15 years",
//     height: "56 - 66",
//     weight: "23 - 41",
//     image: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
//     created: false,
//   },
//   {
//     name: "Chow Chow",
//     temperaments: "Aloof, Loyal, Independent, Quiet",
//     id: 81,
//     life_span: "12 - 15 years",
//     height: "43 - 51",
//     weight: "18 - 32",
//     image: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
//     created: false,
//   },
//   {
//     name: "Clumber Spaniel",
//     temperaments: "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
//     id: 84,
//     life_span: "10 - 12 years",
//     height: "43 - 51",
//     weight: "25 - 39",
//     image: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
//     created: false,
//   },
//   {
//     name: "Cocker Spaniel",
//     temperaments: "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
//     id: 86,
//     life_span: "12 - 15 years",
//     height: "36 - 38",
//     weight: "9 - 14",
//     image: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
//     created: false,
//   },
//   {
//     name: "Cocker Spaniel (American)",
//     temperaments: "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
//     id: 87,
//     life_span: "12 - 15 years",
//     height: "36 - 38",
//     weight: "9 - 14",
//     image: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
//     created: false,
//   },
//   {
//     name: "Coton de Tulear",
//     temperaments:
//       "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
//     id: 89,
//     life_span: "13 - 16 years",
//     height: "23 - 28",
//     weight: "4 - 7",
//     image: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
//     created: false,
//   },
//   {
//     name: "Dalmatian",
//     temperaments:
//       "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
//     id: 92,
//     life_span: "10 - 13 years",
//     height: "48 - 58",
//     weight: "23 - 25",
//     image: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
//     created: false,
//   },
//   {
//     name: "Doberman Pinscher",
//     temperaments:
//       "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
//     id: 94,
//     life_span: "10 years",
//     height: "61 - 71",
//     weight: "30 - 40",
//     image: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
//     created: false,
//   },
//   {
//     name: "Dogo Argentino",
//     temperaments:
//       "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
//     id: 95,
//     life_span: "10 - 12 years",
//     height: "60 - 69",
//     weight: "36 - 45",
//     image: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
//     created: false,
//   },
//   {
//     name: "Dutch Shepherd",
//     temperaments: "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
//     id: 98,
//     life_span: "15 years",
//     height: "56 - 62",
//     weight: "23 - 32",
//     image: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
//     created: false,
//   },
//   {
//     name: "English Setter",
//     temperaments:
//       "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
//     id: 101,
//     life_span: "12 years",
//     height: "61 - 64",
//     weight: "20 - 36",
//     image: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
//     created: false,
//   },
//   {
//     name: "English Shepherd",
//     temperaments: "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
//     id: 102,
//     life_span: "10 - 13 years",
//     height: "46 - 58",
//     weight: "20 - 30",
//     image: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
//     created: false,
//   },
//   {
//     name: "English Springer Spaniel",
//     temperaments:
//       "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
//     id: 103,
//     life_span: "12 - 14 years",
//     height: "48 - 51",
//     weight: "16 - 23",
//     image: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
//     created: false,
//   },
//   {
//     name: "English Toy Spaniel",
//     temperaments: "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
//     id: 104,
//     life_span: "10 - 12 years",
//     height: "25",
//     weight: "4 - 6",
//     image: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
//     created: false,
//   },
//   {
//     name: "English Toy Terrier",
//     temperaments:
//       "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
//     id: 105,
//     life_span: "12 - 13 years",
//     height: "25 - 30",
//     weight: "3 - 4",
//     image: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
//     created: false,
//   },
//   {
//     name: "Eurasier",
//     temperaments: "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
//     id: 107,
//     life_span: "12 - 14 years",
//     height: "52 - 60",
//     weight: "18 - 32",
//     image: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Field Spaniel",
//     temperaments: "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
//     id: 108,
//     life_span: "11 - 15 years",
//     height: "43 - 46",
//     weight: "16 - 23",
//     image: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
//     created: false,
//   },
//   {
//     name: "Finnish Lapphund",
//     temperaments: "Friendly, Keen, Faithful, Calm, Courageous",
//     id: 110,
//     life_span: "12 - 15 years",
//     height: "41 - 53",
//     weight: "15 - 24",
//     image: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
//     created: false,
//   },
//   {
//     name: "Finnish Spitz",
//     temperaments: "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
//     id: 111,
//     life_span: "12 - 15 years",
//     height: "39 - 51",
//     weight: "10 - 13",
//     image: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
//     created: false,
//   },
//   {
//     name: "French Bulldog",
//     temperaments:
//       "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
//     id: 113,
//     life_span: "9 - 11 years",
//     height: "28 - 30",
//     weight: "13",
//     image: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
//     created: false,
//   },
//   {
//     name: "German Pinscher",
//     temperaments:
//       "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
//     id: 114,
//     life_span: "12 - 14 years",
//     height: "43 - 51",
//     weight: "11 - 20",
//     image: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
//     created: false,
//   },
//   {
//     name: "German Shepherd Dog",
//     temperaments:
//       "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
//     id: 115,
//     life_span: "10 - 13 years",
//     height: "56 - 66",
//     weight: "23 - 41",
//     image: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
//     created: false,
//   },
//   {
//     name: "German Shorthaired Pointer",
//     temperaments:
//       "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
//     id: 116,
//     life_span: "12 - 14 years",
//     height: "53 - 64",
//     weight: "20 - 32",
//     image: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Giant Schnauzer",
//     temperaments: "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
//     id: 119,
//     life_span: "10 - 12 years",
//     height: "60 - 70",
//     weight: "29 - 41",
//     image: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
//     created: false,
//   },
//   {
//     name: "Glen of Imaal Terrier",
//     temperaments: "Spirited, Agile, Loyal, Gentle, Active, Courageous",
//     id: 120,
//     life_span: "12 - 15 years",
//     height: "32 - 36",
//     weight: "15 - 18",
//     image: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
//     created: false,
//   },
//   {
//     name: "Golden Retriever",
//     temperaments:
//       "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
//     id: 121,
//     life_span: "10 - 12 years",
//     height: "55 - 61",
//     weight: "25 - 34",
//     image: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
//     created: false,
//   },
//   {
//     name: "Gordon Setter",
//     temperaments: "Fearless, Alert, Loyal, Confident, Gay, Eager",
//     id: 123,
//     life_span: "10 - 12 years",
//     height: "58 - 69",
//     weight: "20 - 36",
//     image: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
//     created: false,
//   },
//   {
//     name: "Great Dane",
//     temperaments: "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
//     id: 124,
//     life_span: "7 - 10 years",
//     height: "71 - 81",
//     weight: "50 - 86",
//     image: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
//     created: false,
//   },
//   {
//     name: "Great Pyrenees",
//     temperaments:
//       "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
//     id: 125,
//     life_span: "10 - 12 years",
//     height: "64 - 81",
//     weight: "39 - 52",
//     image: "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
//     created: false,
//   },
//   {
//     name: "Greyhound",
//     temperaments:
//       "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
//     id: 127,
//     life_span: "10 - 13 years",
//     height: "69 - 76",
//     weight: "23 - 32",
//     image: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
//     created: false,
//   },
//   {
//     name: "Griffon Bruxellois",
//     temperaments:
//       "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
//     id: 128,
//     life_span: "10 – 15 years",
//     height: "23 - 28",
//     weight: "5",
//     image: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
//     created: false,
//   },
//   {
//     name: "Harrier",
//     temperaments:
//       "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
//     id: 129,
//     life_span: "12 - 15 years",
//     height: "46 - 56",
//     weight: "18 - 27",
//     image: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
//     created: false,
//   },
//   {
//     name: "Havanese",
//     temperaments:
//       "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
//     id: 130,
//     life_span: "14 - 15 years",
//     height: "22 - 29",
//     weight: "3 - 6",
//     image: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
//     created: false,
//   },
//   {
//     name: "Irish Setter",
//     temperaments:
//       "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
//     id: 134,
//     life_span: "10 - 11 years",
//     height: "61 - 69",
//     weight: "16 - 32",
//     image: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
//     created: false,
//   },
//   {
//     name: "Irish Terrier",
//     temperaments:
//       "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
//     id: 135,
//     life_span: "12 - 16 years",
//     height: "46",
//     weight: "11 - 12",
//     image: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
//     created: false,
//   },
//   {
//     name: "Irish Wolfhound",
//     temperaments:
//       "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
//     id: 137,
//     life_span: "6 - 8 years",
//     height: "76 - 89",
//     weight: "48 - 82",
//     image: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
//     created: false,
//   },
//   {
//     name: "Italian Greyhound",
//     temperaments:
//       "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
//     id: 138,
//     life_span: "12 - 15 years",
//     height: "33 - 38",
//     weight: "3 - 7",
//     image: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
//     created: false,
//   },
//   {
//     name: "Japanese Chin",
//     temperaments: "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
//     id: 140,
//     life_span: "12 - 14 years",
//     height: "20 - 28",
//     weight: "2 - 4",
//     image: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
//     created: false,
//   },
//   {
//     name: "Japanese Spitz",
//     temperaments:
//       "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
//     id: 141,
//     life_span: "10 – 16 years",
//     height: "30 - 38",
//     weight: "7 - 9",
//     image: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
//     created: false,
//   },
//   {
//     name: "Keeshond",
//     temperaments: "Agile, Obedient, Playful, Quick, Sturdy, Bright",
//     id: 142,
//     life_span: "12 - 15 years",
//     height: "43 - 46",
//     weight: "16 - 20",
//     image: "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
//     created: false,
//   },
//   {
//     name: "Komondor",
//     temperaments: "Steady, Fearless, Affectionate, Independent, Gentle, Calm",
//     id: 144,
//     life_span: "10 - 12 years",
//     height: "65 - 70",
//     weight: "36 - 45",
//     image: "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
//     created: false,
//   },
//   {
//     name: "Kooikerhondje",
//     temperaments: "Benevolent, Agile, Alert, Intelligent, Active, Territorial",
//     id: 145,
//     life_span: "12 - 15 years",
//     height: "36 - 41",
//     weight: "9 - 14",
//     image: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
//     created: false,
//   },
//   {
//     name: "Kuvasz",
//     temperaments:
//       "Clownish, Loyal, Patient, Independent, Intelligent, Protective",
//     id: 147,
//     life_span: "8 - 10 years",
//     height: "66 - 76",
//     weight: "32 - 52",
//     image: "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
//     created: false,
//   },
//   {
//     name: "Labrador Retriever",
//     temperaments:
//       "Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered",
//     id: 149,
//     life_span: "10 - 13 years",
//     height: "55 - 62",
//     weight: "25 - 36",
//     image: "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
//     created: false,
//   },
//   {
//     name: "Lagotto Romagnolo",
//     temperaments: "Keen, Loyal, Companionable, Loving, Active, Trainable",
//     id: 151,
//     life_span: "14 - 16 years",
//     height: "41 - 48",
//     weight: "11 - 16",
//     image: "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
//     created: false,
//   },
//   {
//     name: "Lancashire Heeler",
//     temperaments: "Clever, Friendly, Alert, Intelligent",
//     id: 153,
//     life_span: "12 – 15 years",
//     height: "25 - 30",
//     weight: "3 - 6",
//     image: "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
//     created: false,
//   },
//   {
//     name: "Leonberger",
//     temperaments: "Obedient, Fearless, Loyal, Companionable, Adaptable, Loving",
//     id: 155,
//     life_span: "6 - 8 years",
//     height: "65 - 80",
//     weight: "54 - 77",
//     image: "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
//     created: false,
//   },
//   {
//     name: "Lhasa Apso",
//     temperaments:
//       "Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent",
//     id: 156,
//     life_span: "12 - 15 years",
//     height: "25 - 28",
//     weight: "5 - 8",
//     image: "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
//     created: false,
//   },
//   {
//     name: "Maltese",
//     temperaments:
//       "Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active",
//     id: 161,
//     life_span: "15 - 18 years",
//     height: "20 - 25",
//     weight: "2 - 3",
//     image: "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
//     created: false,
//   },
//   {
//     name: "Miniature American Shepherd",
//     temperaments: "Energetic, Loyal, Intelligent, Trainable",
//     id: 165,
//     life_span: "12 - 15 years",
//     height: "33 - 46",
//     weight: "9 - 18",
//     image: "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
//     created: false,
//   },
//   {
//     name: "Miniature Pinscher",
//     temperaments: "Clever, Outgoing, Friendly, Energetic, Responsive, Playful",
//     id: 167,
//     life_span: "15 years",
//     height: "25 - 32",
//     weight: "4 - 5",
//     image: "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
//     created: false,
//   },
//   {
//     name: "Miniature Schnauzer",
//     temperaments: "Fearless, Friendly, Spirited, Alert, Obedient, Intelligent",
//     id: 168,
//     life_span: "12 - 14 years",
//     height: "30 - 36",
//     weight: "5 - 9",
//     image: "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
//     created: false,
//   },
//   {
//     name: "Newfoundland",
//     temperaments: "Sweet-Tempered, Gentle, Trainable",
//     id: 171,
//     life_span: "8 - 10 years",
//     height: "66 - 71",
//     weight: "45 - 68",
//     image: "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
//     created: false,
//   },
//   {
//     name: "Norfolk Terrier",
//     temperaments:
//       "Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable",
//     id: 172,
//     life_span: "12 - 15 years",
//     height: "23 - 25",
//     weight: "5 - 5",
//     image: "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
//     created: false,
//   },
//   {
//     name: "Norwich Terrier",
//     temperaments: "Hardy, Affectionate, Energetic, Sensitive, Intelligent",
//     id: 176,
//     life_span: "12 - 15 years",
//     height: "25",
//     weight: "5 - 5",
//     image: "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
//     created: false,
//   },
//   {
//     name: "Nova Scotia Duck Tolling Retriever",
//     temperaments: "Outgoing, Alert, Patient, Intelligent, Loving",
//     id: 177,
//     life_span: "12 - 14 years",
//     height: "43 - 53",
//     weight: "16 - 23",
//     image: "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
//     created: false,
//   },
//   {
//     name: "Old English Sheepdog",
//     temperaments: "Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving",
//     id: 178,
//     life_span: "10 - 12 years",
//     height: "53",
//     weight: "27 - 45",
//     image: "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
//     created: false,
//   },
//   {
//     name: "Olde English Bulldogge",
//     temperaments: "Friendly, Alert, Confident, Loving, Courageous, Strong",
//     id: 179,
//     life_span: "9 – 14 years",
//     height: "38 - 48",
//     weight: "NaN",
//     image: "https://cdn2.thedogapi.com/images/B1d5me547.jpg",
//     created: false,
//   },
//   {
//     name: "Papillon",
//     temperaments: "Hardy, Friendly, Energetic, Alert, Intelligent, Happy",
//     id: 181,
//     life_span: "13 - 17 years",
//     height: "20 - 28",
//     weight: "1 - 5",
//     image: "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
//     created: false,
//   },
//   {
//     name: "Pekingese",
//     temperaments:
//       "Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent",
//     id: 183,
//     life_span: "14 - 18 years",
//     height: "15 - 23",
//     weight: "6",
//     image: "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Pembroke Welsh Corgi",
//     temperaments: "Tenacious, Outgoing, Friendly, Bold, Playful, Protective",
//     id: 184,
//     life_span: "12 - 14 years",
//     height: "25 - 30",
//     weight: "11 - 14",
//     image: "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
//     created: false,
//   },
//   {
//     name: "Perro de Presa Canario",
//     temperaments: "Strong Willed, Suspicious, Gentle, Dominant, Calm",
//     id: 185,
//     life_span: "10 - 12 years",
//     height: "56 - 65",
//     weight: "40 - 50",
//     image: "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
//     created: false,
//   },
//   {
//     name: "Pharaoh Hound",
//     temperaments:
//       "Affectionate, Sociable, Playful, Intelligent, Active, Trainable",
//     id: 188,
//     life_span: "12 - 14 years",
//     height: "53 - 64",
//     weight: "18 - 27",
//     image: "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
//     created: false,
//   },
//   {
//     name: "Plott",
//     temperaments: "Bold, Alert, Loyal, Intelligent",
//     id: 189,
//     life_span: "12 - 14 years",
//     height: "51 - 64",
//     weight: "18 - 27",
//     image: "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
//     created: false,
//   },
//   {
//     name: "Pomeranian",
//     temperaments:
//       "Extroverted, Friendly, Sociable, Playful, Intelligent, Active",
//     id: 193,
//     life_span: "15 years",
//     height: "20 - 30",
//     weight: "1 - 3",
//     image: "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
//     created: false,
//   },
//   {
//     name: "Poodle (Miniature)",
//     id: 196,
//     life_span: "12 – 15 years",
//     height: "28 - 38",
//     weight: "7 - 8",
//     image: "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
//     created: false,
//   },
//   {
//     name: "Poodle (Toy)",
//     id: 197,
//     life_span: "18 years",
//     height: "23 - 28",
//     weight: "3 - 4",
//     image: "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
//     created: false,
//   },
//   {
//     name: "Pug",
//     temperaments:
//       "Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive",
//     id: 201,
//     life_span: "12 - 14 years",
//     height: "25 - 30",
//     weight: "6 - 8",
//     image: "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
//     created: false,
//   },
//   {
//     name: "Puli",
//     temperaments: "Energetic, Agile, Loyal, Obedient, Intelligent, Faithful",
//     id: 204,
//     life_span: "12 - 16 Years years",
//     height: "41 - 43",
//     weight: "11 - 16",
//     image: "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
//     created: false,
//   },
//   {
//     name: "Pumi",
//     temperaments: "Lively, Reserved, Intelligent, Active, Protective, Vocal",
//     id: 205,
//     life_span: "13 - 15 years",
//     height: "38 - 47",
//     weight: "8 - 15",
//     image: "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
//     created: false,
//   },
//   {
//     name: "Rat Terrier",
//     temperaments:
//       "Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving",
//     id: 207,
//     life_span: "12 - 18 years",
//     height: "25 - 33",
//     weight: "4 - 11",
//     image: "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
//     created: false,
//   },
//   {
//     name: "Redbone Coonhound",
//     temperaments:
//       "Affectionate, Energetic, Independent, Companionable, Familial, Unflappable",
//     id: 208,
//     life_span: "10 - 12 years",
//     height: "53 - 69",
//     weight: "20 - 36",
//     image: "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
//     created: false,
//   },
//   {
//     name: "Rhodesian Ridgeback",
//     temperaments:
//       "Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent",
//     id: 209,
//     life_span: "10 - 12 years",
//     height: "61 - 69",
//     weight: "34 - 36",
//     image: "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
//     created: false,
//   },
//   {
//     name: "Rottweiler",
//     temperaments:
//       "Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous",
//     id: 210,
//     life_span: "8 - 10 years",
//     height: "56 - 69",
//     weight: "34 - 50",
//     image: "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
//     created: false,
//   },
//   {
//     name: "Russian Toy",
//     id: 211,
//     life_span: "10 - 12 years",
//     height: "19 - 27",
//     weight: "1 - 3",
//     image: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
//     created: false,
//   },
//   {
//     name: "Saint Bernard",
//     temperaments: "Friendly, Lively, Gentle, Watchful, Calm",
//     id: 212,
//     life_span: "7 - 10 years",
//     height: "65 - 70",
//     weight: "59 - 82",
//     image: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
//     created: false,
//   },
//   {
//     name: "Saluki",
//     temperaments: "Aloof, Reserved, Intelligent, Quiet",
//     id: 213,
//     life_span: "12 - 14 years",
//     height: "58 - 71",
//     weight: "16 - 29",
//     image: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
//     created: false,
//   },
//   {
//     name: "Samoyed",
//     temperaments: "Stubborn, Friendly, Sociable, Lively, Alert, Playful",
//     id: 214,
//     life_span: "12 - 14 years",
//     height: "48 - 60",
//     weight: "23 - 27",
//     image: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Schipperke",
//     temperaments: "Fearless, Agile, Curious, Independent, Confident, Faithful",
//     id: 216,
//     life_span: "13 - 15 years",
//     height: "25 - 33",
//     weight: "5 - 7",
//     image: "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
//     created: false,
//   },
//   {
//     name: "Scottish Deerhound",
//     temperaments: "Docile, Friendly, Dignified, Gentle",
//     id: 218,
//     life_span: "8 - 10 years",
//     height: "71 - 81",
//     weight: "32 - 59",
//     image: "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
//     created: false,
//   },
//   {
//     name: "Scottish Terrier",
//     temperaments: "Feisty, Alert, Independent, Playful, Quick, Self-assured",
//     id: 219,
//     life_span: "11 - 13 years",
//     height: "25",
//     weight: "8 - 10",
//     image: "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
//     created: false,
//   },
//   {
//     name: "Shetland Sheepdog",
//     temperaments:
//       "Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong",
//     id: 221,
//     life_span: "12 - 14 years",
//     height: "33 - 41",
//     weight: "14",
//     image: "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
//     created: false,
//   },
//   {
//     name: "Shiba Inu",
//     temperaments: "Charming, Fearless, Keen, Alert, Confident, Faithful",
//     id: 222,
//     life_span: "12 - 16 years",
//     height: "34 - 42",
//     weight: "8 - 10",
//     image: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
//     created: false,
//   },
//   {
//     name: "Shih Tzu",
//     temperaments:
//       "Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous",
//     id: 223,
//     life_span: "10 - 18 years",
//     height: "20 - 28",
//     weight: "4 - 7",
//     image: "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
//     created: false,
//   },
//   {
//     name: "Shiloh Shepherd",
//     temperaments: "Outgoing, Loyal, Companionable, Gentle, Loving, Trainable",
//     id: 225,
//     life_span: "9 – 14 years",
//     height: "66 - 76",
//     weight: "54 - 64",
//     image: "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
//     created: false,
//   },
//   {
//     name: "Siberian Husky",
//     temperaments: "Outgoing, Friendly, Alert, Gentle, Intelligent",
//     id: 226,
//     life_span: "12 years",
//     height: "51 - 60",
//     weight: "16 - 27",
//     image: "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
//     created: false,
//   },
//   {
//     name: "Silky Terrier",
//     temperaments: "Friendly, Responsive, Inquisitive, Alert, Quick, Joyful",
//     id: 228,
//     life_span: "12 - 15 years",
//     height: "23 - 25",
//     weight: "4 - 5",
//     image: "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Smooth Fox Terrier",
//     temperaments: "Fearless, Affectionate, Alert, Playful, Intelligent, Active",
//     id: 232,
//     life_span: "12 - 14 years",
//     height: "39",
//     weight: "NaN - 8",
//     image: "https://cdn2.thedogapi.com/images/Syszjx9Em.jpg",
//     created: false,
//   },
//   {
//     name: "Soft Coated Wheaten Terrier",
//     temperaments:
//       "Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful",
//     id: 233,
//     life_span: "12 - 15 years",
//     height: "41 - 46",
//     weight: "14 - 18",
//     image: "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
//     created: false,
//   },
//   {
//     name: "Spanish Water Dog",
//     temperaments:
//       "Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent",
//     id: 235,
//     life_span: "12 - 15 years",
//     height: "41 - 51",
//     weight: "14 - 23",
//     image: "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
//     created: false,
//   },
//   {
//     name: "Spinone Italiano",
//     temperaments: "Docile, Friendly, Affectionate, Loyal, Patient, Gentle",
//     id: 236,
//     life_span: "10 - 12 years",
//     height: "57 - 70",
//     weight: "28 - 39",
//     image: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
//     created: false,
//   },
//   {
//     name: "Staffordshire Bull Terrier",
//     temperaments:
//       "Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous",
//     id: 238,
//     life_span: "12 - 14 years",
//     height: "36 - 41",
//     weight: "11 - 17",
//     image: "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
//     created: false,
//   },
//   {
//     name: "Standard Schnauzer",
//     temperaments:
//       "Trainable, Good-natured, Devoted, Lively, Playful, Intelligent",
//     id: 239,
//     life_span: "13 - 15 years",
//     height: "44 - 50",
//     weight: "14 - 23",
//     image: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
//     created: false,
//   },
//   {
//     name: "Swedish Vallhund",
//     temperaments: "Fearless, Friendly, Energetic, Alert, Intelligent, Watchful",
//     id: 242,
//     life_span: "12 - 14 years",
//     height: "29 - 34",
//     weight: "9 - 14",
//     image: "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
//     created: false,
//   },
//   {
//     name: "Thai Ridgeback",
//     temperaments:
//       "Protective, Loyal, Independent, Intelligent, Loving, Familial",
//     id: 243,
//     life_span: "10 - 12 years",
//     height: "51 - 61",
//     weight: "16 - 25",
//     image: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
//     created: false,
//   },
//   {
//     name: "Tibetan Mastiff",
//     temperaments:
//       "Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective",
//     id: 244,
//     life_span: "10 - 14 years",
//     height: "61 - 66",
//     weight: "39 - 64",
//     image: "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
//     created: false,
//   },
//   {
//     name: "Tibetan Spaniel",
//     temperaments:
//       "Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy",
//     id: 245,
//     life_span: "12 - 15 years",
//     height: "25",
//     weight: "4 - 7",
//     image: "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
//     created: false,
//   },
//   {
//     name: "Tibetan Terrier",
//     temperaments:
//       "Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive",
//     id: 246,
//     life_span: "12 - 15 years",
//     height: "36 - 43",
//     weight: "9 - 11",
//     image: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
//     created: false,
//   },
//   {
//     name: "Toy Fox Terrier",
//     temperaments: "Friendly, Spirited, Alert, Loyal, Playful, Intelligent",
//     id: 248,
//     life_span: "12 - 15 years",
//     height: "20 - 28",
//     weight: "2 - 4",
//     image: "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
//     created: false,
//   },
//   {
//     name: "Treeing Walker Coonhound",
//     temperaments:
//       "Clever, Affectionate, Confident, Intelligent, Loving, Trainable",
//     id: 250,
//     life_span: "10 - 13 years",
//     height: "51 - 69",
//     weight: "20 - 36",
//     image: "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
//     created: false,
//   },
//   {
//     name: "Vizsla",
//     temperaments: "Affectionate, Energetic, Loyal, Gentle, Quiet",
//     id: 251,
//     life_span: "10 - 14 years",
//     height: "53 - 61",
//     weight: "23 - 29",
//     image: "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
//     created: false,
//   },
//   {
//     name: "Weimaraner",
//     temperaments:
//       "Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast",
//     id: 253,
//     life_span: "12 - 15 years",
//     height: "58 - 69",
//     weight: "25 - 41",
//     image: "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
//     created: false,
//   },
//   {
//     name: "Welsh Springer Spaniel",
//     temperaments: "Stubborn, Friendly, Affectionate, Loyal, Playful, Active",
//     id: 254,
//     life_span: "12 - 15 years",
//     height: "43 - 48",
//     weight: "16 - 25",
//     image: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
//     created: false,
//   },
//   {
//     name: "West Highland White Terrier",
//     temperaments:
//       "Hardy, Friendly, Alert, Independent, Gay, Active, Courageous",
//     id: 256,
//     life_span: "15 - 20 years",
//     height: "25 - 28",
//     weight: "7 - 10",
//     image: "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
//     created: false,
//   },
//   {
//     name: "Whippet",
//     temperaments: "Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet",
//     id: 257,
//     life_span: "12 - 15 years",
//     height: "46 - 56",
//     weight: "11 - 16",
//     image: "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
//     created: false,
//   },
//   {
//     name: "White Shepherd",
//     temperaments:
//       "Self-confidence, Aloof, Fearless, Alert, Companionable, Eager",
//     id: 258,
//     life_span: "12 – 14 years",
//     height: "56 - 64",
//     weight: "27 - 39",
//     image: "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
//     created: false,
//   },
//   {
//     name: "Wire Fox Terrier",
//     temperaments: "Fearless, Friendly, Bold, Keen, Alert, Quick",
//     id: 259,
//     life_span: "13 – 14 years",
//     height: "33 - 41",
//     weight: "7 - 9",
//     image: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
//     created: false,
//   },
//   {
//     name: "Wirehaired Pointing Griffon",
//     temperaments: "Loyal, Gentle, Vigilant, Trainable, Proud",
//     id: 260,
//     life_span: "12 - 14 years",
//     height: "51 - 61",
//     weight: "20 - 32",
//     image: "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
//     created: false,
//   },
//   {
//     name: "Wirehaired Vizsla",
//     id: 261,
//     life_span: "12 - 14 years",
//     height: "55 - 64",
//     weight: "20 - 29",
//     image: "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
//     created: false,
//   },
//   {
//     name: "Xoloitzcuintli",
//     temperaments:
//       "Cheerful, Alert, Companionable, Intelligent, Protective, Calm",
//     id: 262,
//     life_span: "12 - 14 years",
//     height: "25 - 58",
//     weight: "4 - 14",
//     image: "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
//     created: false,
//   },
//   {
//     name: "Yorkshire Terrier",
//     temperaments: "Bold, Independent, Confident, Intelligent, Courageous",
//     id: 264,
//     life_span: "12 - 16 years",
//     height: "20 - 23",
//     weight: "2 - 3",
//     image: "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
//     created: false,
//   },
// ];

// // console.log(s.includes("Bold"));

// let Fil = s;
// console.log(Fil);
let temp="